### PR TITLE
Removed old `solve` and replaced `ode`->`solve`

### PR DESCRIPTION
**Pull request by mauro3**
Also updated the iterator-implementation.jl such that it can be run.

### CODE REVIEW

**Comment by pwl** [comment]
I thought about it for a long time and, although I get your idea with `Problem` being the numerical problem to solve I still don't like the name nor the constructor being used explicitly in our API.  It doesn't save us lines of code or makes the whole design simpler (`solve` is essentially the same as `Problem`), and at the same time it leaves us less flexible if we want to change the internal implementation of iterators.  Say, redesign or rename the `Problem` type to something else.

**Comment by mauro3** [comment]
Sounds good, let's call the function `problem` then.

**Comment by pwl** [comment]
You've probably noticed that we can call `solve(ivp)` now, without specifying the algorithm explicitly.  If we rename `solve` to `problem` we would have calls like `problem(ivp)`, which is essentially `problem(initial value problem)`.  I think this might cause too much confusion.

**Comment by mauro3** [comment]
What is also confusing though is that `solve(ivp)` does not solve the ivp.

**Comment by mauro3** [comment]
Let's try and fine another word.  I think a noun is more appropriate as this creates an instance and doesn't actually do very much.

**Comment by pwl** [comment]
How about `solve` -> `solver`?  `Solver` is not a solution, that's clear, but at the same time it explicitly offers to solve your problem.  But then we would have to rename `AbstractSolver` to something else.

**Comment by mauro3** [comment]
I think it would be nice and intuitive to have `solve` as the main high and mid-level user interface:

```
prob = we_dont_know_what_its_called(ivp, RK45)
t,y = solve(prob)
# but also
t,y = solve(F, y0, t, RK45)
```

if we go that way, then `solver` is no good as it is confusing.

**Comment by pwl** [comment]
These ideas were introduced in #19, closing.

**Pull request closed without merging**
